// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 countsubstring() ", "[example]")
{
	int cnt;

	cnt = countsubstring("th");
	cout << "The count of occurrence " << cnt << endl;

	INFO("The result should  17\n");
	REQUIRE(cnt == 17);
	cout << "--------------------------------------------------\n";

	// REQUIRE(number[idx] == usernum);
}

TEST_CASE("Ex2 countsubstring() ", "[example]")
{
	int cnt;

	cnt = countsubstring("la");
	cout << "The count of occurrence " << cnt << endl;

	INFO("The result should  5\n");
	REQUIRE(cnt == 5);
	cout << "--------------------------------------------------\n";

	// REQUIRE(number[idx] == usernum);
}